language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    # This is broken at this time due to a phpspec issue.
    # @see https://github.com/jhedstrom/DrupalDriver/issues/172
    - php: hhvm

install:
  - composer install

script:
  - composer test

# Enable Travis containers.
sudo: false
